{{- range .Values.secrets }}
{{- template "common.secret-from-file-strings" . }}
{{- end }}

{{- range .Values.infoSecrets }}
{{- template "common.secret-from-file-strings" . }}
{{- end }}

{{- range .Values.engineSecrets }}
{{- template "common.secret-from-file-strings" . }}
{{- end }}

{{- range .Values.schemaSecrets }}
{{- template "common.secret-from-file-strings" . }}
{{- end }}