# add a service and deployment for testing
whoami: false


# these are converted to configmaps and added to pods as env vars
# configmaps are named <chart_name>-<env_group_name> (eg: common)
# added to all deployments/pods so they must be common
# for deployment specific add them to deployment.env
env: []
# - name: common
#   vars:
#     SHELL: /bin/bash


datasets: []


# file names of secret keys for cloudvolume
# these will be mounted as volumes
# eg: if a file name is secret.json
# volume.name: secret, subPath: secret.json
# mountPath: /root/.cloudvolume/secrets
# NOTE: this assumes kubernetes secrets are already present.
# this limitation is because Helm does not support
# loading files external to a chart for security reasons.
cloudVolumeSecrets: []


readService:
  enabled: &readServiceEnabled false
  name: &readServiceName "chunkedgraph-read"
  annotations: {}
  type: ClusterIP
  ports: []
readDeployment:
  enabled: *readServiceEnabled
  name: *readServiceName
  affinity: {}
  nodeSelector: {}
  annotations: {}
  image:
    repository: null
    tag: null
    pullPolicy: Always
  command: []
  env: []
  replicaCount: 1
  ports: []
  resources:
    requests:
      cpu: 450m
      memory: 1.5G
  hpa:
    enabled: false
    minReplicas: 3
    maxReplicas: 30
    targetMem: 85
    targetCPU: 95


editService:
  enabled: &editServiceEnabled false
  name: &editServiceName "chunkedgraph-edit"
  annotations: {}
  type: ClusterIP
  ports: []
editDeployment:
  enabled: *editServiceEnabled
  name: *editServiceName
  affinity: {}
  nodeSelector: {}
  annotations: {}
  command: []
  image:
    repository: null
    tag: null
    pullPolicy: Always
  env: []
  replicaCount: 1
  ports: []
  resources:
    requests:
      cpu: 600m
      memory: 2G
  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetMem: 85
    targetCPU: 85


meshService:
  enabled: &meshServiceEnabled false
  name: &meshServiceName "chunkedgraph-mesh"
  annotations: {}
  type: ClusterIP
  ports: []
meshDeployment:
  enabled: *meshServiceEnabled
  name: *meshServiceName
  affinity: {}
  nodeSelector: {}
  annotations: {}
  command: []
  image:
    repository: null
    tag: null
    pullPolicy: Always
  env: []
  replicaCount: 1
  ports: []
  resources:
    requests:
      cpu: 450m
      memory: 1.5G
  hpa:
    enabled: false
    minReplicas: 3
    maxReplicas: 15
    targetMem: 90
    targetCPU: 95


remeshService:
  enabled: &remeshServiceEnabled false
  name: &remeshServiceName "chunkedgraph-remesh"
  annotations: {}
  type: ClusterIP
  ports: []
remeshDeployment:
  enabled: *remeshServiceEnabled
  name: *remeshServiceName
  affinity: {}
  nodeSelector: {}
  annotations: {}
  command: []
  image:
    repository: null
    tag: null
    pullPolicy: Always
  env: []
  replicaCount: 1
  ports: []
  resources:
    requests:
      cpu: 1
      memory: 4G
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetMem: 90
    targetCPU: 95
