# add a service and deployment for testing
whoami: false


# common env vars added to all chunkedgraph pods
env: []
# - name: common
#   vars:
#     SHELL: /bin/bash


datasets: []
# example
# - name: wc-lee
#   files:
#   - name: vnc.yml
#     content:
#       graph_id: vnc1_full_v3align_2
#       backend_client:
#         TYPE: bigtable
#         CONFIG:
#           ADMIN: true
#           READ_ONLY: false
#           PROJECT: zetta-lee-fly-vnc-001
#           INSTANCE: chunkedgraphs


secrets: []
# example
# - name: secret-name
#   files:
#     google-secret.json: |-
#       <contents of service account json>


readService:
  enabled: &readServiceEnabled false
  name: &readServiceName "chunkedgraph-read"
  annotations: {}
  type: ClusterIP
  ports: []
readDeployment:
  enabled: *readServiceEnabled
  name: *readServiceName
  helmRollOnUpgrade: true
  affinity: {}
  nodeSelector: {}
  annotations: {}
  image:
    repository: null
    tag: null
    pullPolicy: Always
  volumes: []
  volumeMounts: []
  imagePullSecrets: []
  command: []
  env: []
  replicaCount: 1
  ports: []
  resources:
    requests:
      cpu: 450m
      memory: 1.5G
  hpa:
    enabled: false
    minReplicas: 3
    maxReplicas: 30
    targetMem: 85
    targetCPU: 95


editService:
  enabled: &editServiceEnabled false
  name: &editServiceName "chunkedgraph-edit"
  annotations: {}
  type: ClusterIP
  ports: []
editDeployment:
  enabled: *editServiceEnabled
  name: *editServiceName
  helmRollOnUpgrade: true
  affinity: {}
  nodeSelector: {}
  annotations: {}
  command: []
  image:
    repository: null
    tag: null
    pullPolicy: Always
  volumes: []
  volumeMounts: []
  imagePullSecrets: []
  env: []
  replicaCount: 1
  ports: []
  resources:
    requests:
      cpu: 600m
      memory: 2G
  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetMem: 85
    targetCPU: 85


meshService:
  enabled: &meshServiceEnabled false
  name: &meshServiceName "chunkedgraph-mesh"
  annotations: {}
  type: ClusterIP
  ports: []
meshDeployment:
  enabled: *meshServiceEnabled
  name: *meshServiceName
  helmRollOnUpgrade: true
  affinity: {}
  nodeSelector: {}
  annotations: {}
  command: []
  image:
    repository: null
    tag: null
    pullPolicy: Always
  volumes: []
  volumeMounts: []
  imagePullSecrets: []
  env: []
  replicaCount: 1
  ports: []
  resources:
    requests:
      cpu: 450m
      memory: 1.5G
  hpa:
    enabled: false
    minReplicas: 3
    maxReplicas: 15
    targetMem: 90
    targetCPU: 95


remeshService:
  enabled: &remeshServiceEnabled false
  name: &remeshServiceName "chunkedgraph-remesh"
  annotations: {}
  type: ClusterIP
  ports: []
remeshDeployment:
  enabled: *remeshServiceEnabled
  name: *remeshServiceName
  helmRollOnUpgrade: true
  affinity: {}
  nodeSelector: {}
  annotations: {}
  command: []
  image:
    repository: null
    tag: null
    pullPolicy: Always
  volumes: []
  volumeMounts: []
  imagePullSecrets: []
  env: []
  replicaCount: 1
  ports: []
  resources:
    requests:
      cpu: 1
      memory: 4G
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetMem: 90
    targetCPU: 95
