routes: []

basicAuthMiddlewares: []

chainMiddlewares: []

forwardAuthMiddlewares: []

headerMiddlewares: []

redirectMiddlewares: []

replacePathRegexMiddlwares: []

stripPrefixMiddlewares: []

stripPrefixRegexMiddlewares: []
