# headerMiddlewares: []
# redirectMiddlewares: []
# basicAuthMiddlewares: []
# routes: []

headerMiddlewares:
- name: chunkedgraph-read-wc-lee-header
  headers:
    customRequestHeaders:
      l5d-dst-override: "chunkedgraph-read-wc-lee.default.svc.cluster.local:80"
- name: chunkedgraph-edit-wc-lee-header
  headers:
    customRequestHeaders:
      l5d-dst-override: "chunkedgraph-edit-wc-lee.default.svc.cluster.local:80"
- name: chunkedgraph-mesh-wc-lee-header
  headers:
    customRequestHeaders:
      l5d-dst-override: "chunkedgraph-mesh-wc-lee.default.svc.cluster.local:80"
- name: whoami-wc-lee-header
  headers:
    customRequestHeaders:
      l5d-dst-override: "whoami-wc-lee.default.svc.cluster.local:80"

redirectMiddlewares:
- name: https-only
  redirectScheme:
    scheme: https
    permanent: true

basicAuthMiddlewares:
- name: linkerd-dashboard-auth
  namespace: linkerd
  basicAuth:
    secret: linkerd-auth
- name: wc-lee-auth
  basicAuth:
    secret: wc-lee-auth

routes:
- name: chunkedgraph
  entryPoints:
    - web
  rules:
  - match: &chunkedgraphReadRule PathPrefix(`/segmentation`)
    services: &chunkedgraphReadServices
    - name: chunkedgraph-read
      port: 80
    middlewares:
    - name: https-only
  - match: &chunkedgraphEditRule Path(`/segmentation`, `/segmentation/api/v1/table/{t:[\w\-]+}/merge`, `/segmentation/api/v1/table/{t:[\w\-]+}/split`)
    services: &chunkedgraphEditServices
    - name: chunkedgraph-edit
      port: 80
    middlewares:
    - name: https-only
  - match: &chunkedgraphMeshRule PathPrefix(`/meshing`) || PathPrefix(`/segmentation`)
    services: &chunkedgraphMeshServices
    - name: chunkedgraph-mesh
      port: 80
    middlewares:
    - name: https-only

- name: chunkedgraph-tls
  tls:
    secretName: acme-cert
  entryPoints:
    - websecure
  rules:
  - match: *chunkedgraphReadRule
    services: *chunkedgraphReadServices
  - match: *chunkedgraphEditRule
    services: *chunkedgraphEditServices
  - match: *chunkedgraphMeshRule
    services: *chunkedgraphMeshServices

- name: whoami
  entryPoints:
    - web
  rules:
  - match: &whoamiRule Path(`/`, `/whoami`)
    services: &whoamiServices
      - name: whoami
        port: 80
    middlewares:
    - name: https-only

- name: whoami-tls
  tls:
    secretName: acme-cert
  entryPoints:
    - websecure
  rules:
  - match: *whoamiRule
    services: *whoamiServices
    middlewares:
    - name: wc-lee-auth

