# env configmaps from values file
{{- range .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" $.Chart.Name .name }}
data:
  {{- range $key, $val := .vars }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
{{- end}}