apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | quote }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    app: {{ .Chart.Name | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol | quote }}
      name: {{ .Values.service.portName | quote }}
  selector:
    app: {{ .Chart.Name | quote }}
