apiVersion: v1
entries:
  chunkedgraph:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-09-18T13:19:00.720449789+05:30"
    description: Deployment for chunkedgraph APIs.
    digest: 5f7feaac081ef03fddb7bff7a9fc3eb503a56e11e4452b63314a88267d2c1c6e
    name: chunkedgraph
    type: application
    urls:
    - chunkedgraph-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-09-18T13:19:00.719347247+05:30"
    description: Deployment for chunkedgraph APIs.
    digest: 7347a614567618e74dcb75f6039e970dc434329b11fadb28681e69b10dadcf40
    name: chunkedgraph
    type: application
    urls:
    - chunkedgraph-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-09-18T13:19:00.718307823+05:30"
    description: Deployment for chunkedgraph APIs.
    digest: 16f62fd5869ddf5fd561778d4b2a57f5751e4486339f30fe06001ec18048fec7
    name: chunkedgraph
    type: application
    urls:
    - chunkedgraph-0.2.0.tgz
    version: 0.2.0
  linkerd-mtls:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-09-18T13:19:00.721001598+05:30"
    description: |-
      Installs supporting elements for Linkerd multicluster communication.
      Assumes that cert-manager is installed.
    digest: 132742ed5334b5289bac2a90a44a6f91e694d496d02115659040076d28931684
    name: linkerd-mtls
    type: application
    urls:
    - linkerd-mtls-0.1.0.tgz
    version: 0.1.0
  traefik-routes:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-09-18T13:19:00.721905236+05:30"
    description: |-
      Chart for installing traefik routes. Requires Traefik Kubernetes CRDs.
      Includes template helpers for routes and middlewares.
      Currently supports only 3 entrypoints web(80), websecure(443) and traefik(8080).
    digest: f0f03b7b65d03b810b7b322b43fd2726abdae5b516dc9c60b08bdf14854f2a41
    name: traefik-routes
    type: application
    urls:
    - traefik-routes-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-09-18T13:19:00.72147295+05:30"
    description: |-
      Chart for installing traefik routes. Requires Traefik Kubernetes CRDs.
      Includes template helpers for routes and middlewares.
      Currently supports only 3 entrypoints web(80), websecure(443) and traefik(8080).
    digest: 4629c23d2631019ce394f68d6e7fdc3a1f8f1431758fb32e5ab9543f9bbd8581
    name: traefik-routes
    type: application
    urls:
    - traefik-routes-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-18T13:19:00.717179707+05:30"
