apiVersion: v1
entries:
  chunkedgraph:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-08-16T16:21:25.44717186+05:30"
    description: Deployment for chunkedgraph APIs.
    digest: 8e9ace357232bf24bfd187a3d9f1a1c4a151be579adcb000d6c021427ead97fb
    name: chunkedgraph
    type: application
    urls:
    - chunkedgraph-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-16T16:21:25.445677255+05:30"
