secrets: []
# example
# - name: secret-name
#   files:
#     google-secret.json: |-
#       <contents of service account json>


stateService:
  enabled: &stateServiceEnabled false
  name: &stateServiceName "state-server"
  annotations: {}
  type: ClusterIP
  ports: []
stateDeployment:
  enabled: *stateServiceEnabled
  name: *stateServiceName
  helmRollOnUpgrade: true
  affinity: {}
  nodeSelector: {}
  annotations: {}
  containers: []
  hpa:
    enabled: false
    minReplicas: 3
    maxReplicas: 10
    targetMem: 75
    targetCPU: 90