apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.trustAnchorName }}
  namespace: {{ .Values.namespace }}
data:
  tls.crt: |-
    {{ .Values.certificateAuthority.crt | b64enc }}
  tls.key: |-
    {{ .Values.certificateAuthority.key | b64enc }}
type: kubernetes.io/tls