{{- range .Values.headerMiddlewares }}
{{- template "traefik.headerMiddleware" . }}
{{- end }}

{{- range .Values.redirectMiddlewares }}
{{- template "traefik.redirectMiddleware" . }}
{{- end }}

{{- range .Values.basicAuthMiddlewares }}
{{- template "traefik.basicAuthMiddleware" . }}
{{- end }}

{{- range .Values.stripPrefixMiddlewares }}
{{- template "traefik.stripPrefixMiddleware" . }}
{{- end }}

{{- range .Values.chainMiddlewares }}
{{- template "traefik.chainMiddleware" . }}
{{- end }}

