{{- range .Values.chainMiddlewares }}
{{- $obj := mustMerge . (dict "Release" $.Release.Name) -}}
{{- template "traefik.chainMiddleware" $obj }}
{{- end }}

{{- range .Values.headerMiddlewares }}
{{- $obj := mustMerge . (dict "Release" $.Release.Name) -}}
{{- template "traefik.headerMiddleware" $obj }}
{{- end }}

{{- range .Values.redirectMiddlewares }}
{{- $obj := mustMerge . (dict "Release" $.Release.Name) -}}
{{- template "traefik.redirectMiddleware" $obj }}
{{- end }}

{{- range .Values.basicAuthMiddlewares }}
{{- $obj := mustMerge . (dict "Release" $.Release.Name) -}}
{{- template "traefik.basicAuthMiddleware" $obj }}
{{- end }}

{{- range .Values.stripPrefixMiddlewares }}
{{- $obj := mustMerge . (dict "Release" $.Release.Name) -}}
{{- template "traefik.stripPrefixMiddleware" $obj }}
{{- end }}

{{- range .Values.forwardAuthMiddlewares }}
{{- $obj := mustMerge . (dict "Release" $.Release.Name) -}}
{{- template "traefik.forwardAuthMiddleware" $obj }}
{{- end }}

